name: "Setup .NET"
description: |
  Installs .NET and restores dependencies.
inputs:
  build:
    description: "Whether to build the project after restoring dependencies"
    required: false
    default: 'true'

runs:
  using: composite
  steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x.x

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./
        shell: bash

      - name: Restore Tools
        run: dotnet tool restore
        working-directory: ./
        shell: bash

      - name: Build Project
        if: ${{ inputs.build == 'true' }}
        run: dotnet build --configuration Release --no-restore
        working-directory: ./
        shell: bash
