env:
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

name: "C# and .NET Checks"
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, auto_merge_enabled]
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_SHA }}

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./Aptos.Tests
        shell: bash

  run-format-check:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_SHA }}

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet
        with:
          build: false

      - name: Check Formatting
        uses: ./.github/actions/check-formatting
